### ISSUE TITLE
Send a hint every X minutes

### ISSUE THREAD

**Issue by Kaffeine** [infclass/teeworlds-infclassR#93]
Make the server sending chat messages with some useful and unobvious information. E.g.:
- "Hunter receives no knockback from Medic's shotgun"
- "Merc's grenades prevent zombies from healing"
- "Hero's flags fully restore ammo"
- "Smoker has livesteal"
- "Taxi prevents ammo regen"

Suggested by @Intramint

Add the messages to `infcgamecontroller.cpp`, add a config variable to define the interval and use time_get() somewhere in `CInfClassGameController::Tick()` to measure it. Don't print anything if `NumPlayers == 0`. Make the messages translatable:
 ```cpp
static const char *aHintMessages[] = {
	_("Hint1"),
	_("Hint2"),
};
```

**Comment by Intramint** [comment]
- Taxi prevents ammo regeneration for all passengers.
- Choosing a random class grants full armor.
- You can toggle hook protection by pressing f3 ("Vote yes" keybind).
- Mercenary can reduce ammo usage during flight by tapping instead of holding down the "fire" button.
- Mercenary's grenades prevent zombies from healing.
- Medic can heal Heroes using the grenade launcher.
- Medic and Biologist can use hammer to instantly kill an infected.
- Hero can stand still for a short time to be pointed towards the flag.
- Hero's turrets are great for detecting Ghosts.
- Hero can withstand a hit when on at least __ HP and __ will receive __ damage.
- Hero's flags fully restore ammo to all humans
- Engineer's wall's lifespan gets reduced by __ seconds when an infected dies on it.
- Soldier's bombs can hit through walls.
- Ninja's slash deals 9 damage by default. One more pistol shot will kill an infected with no armor. 
- Ninja with a single strength upgrade can kill an armorless infected with a single slash.
- Ninja doesn't need to directly kill their target. An assist with a laser blind or grenade stun will still grant the rewards.
- Ninja heals slightly on a target kill.
- Sniper deals double(triple?) damage in locked position.
- Scientist can use Taxi to teleport his teammates into safety.
- Scientist can get a white hole after 15 kills.
- Scientist can rocket jump with the laser rifle.
- Biologist's bouncy shotgun can be used to hit the infected around corners.
- Smoker heals by hooking humans.
- Boomer can infect through narrow walls.
- Hunter receives no knockback from Medic's shotgun.
- Bat can heal by hitting humans.
- Spider doesn't need to be in Web mode to automatically grab any humans touching its hook.
- Spider can be hooked and transported by teammates to extend its hook trap.
- Slug can heal itself and allies over time up to 13 HP with its slime.
- Slug can hold down the "fire" button to automatically spread slime. The hammer swings won't hurt humans this way though.
- Voodoo can unfreeze an Undead while in Spirit mode.
- Witch can spawn the infected through narrow walls.
- Undead can be removed from a game by throwing it into kill tiles or reviving it as a Medic.

There are some custom values that should be taken from the server config similarly to how help pages do it. Also i wasn't sure about Sniper's locked position damage so that needs to be corrected to show the correct information (double or triple)

**Comment by Kaffeine** [comment]
(Implemented in https://github.com/infclass/teeworlds-infclassR/pull/95)
